Imports DevExpress.XtraPivotGrid
Imports DevExpress.Data.PivotGrid
Public Class Form1

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        CustomerReportsTableAdapter1.Fill(NwindDataSet1.CustomerReports)
        Dim expression As New ExpressionDataBinding()
        expression.Expression = "Iif(IsTotal([fieldCompanyName]), 'Grand Total', IsTotal([fieldYear]), 'Grand Total', IsTotal([fieldProductName]), 'Total', IsTotal([fieldQuarter]), 'Total', Sum([ProductAmount]))"
        fieldProductAmount1.DataBinding = expression
    End Sub

End Class
