Imports DevExpress.XtraPivotGrid
Imports DevExpress.Data.PivotGrid
Public Class Form1

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        CustomerReportsTableAdapter1.Fill(NwindDataSet1.CustomerReports)
        fieldProductAmount1.SummaryType = PivotSummaryType.Custom

    End Sub

    Private Sub pivotGridControl1_CustomSummary(ByVal sender As Object,
                ByVal e As PivotGridCustomSummaryEventArgs) Handles PivotGridControl1.CustomSummary
        If ReferenceEquals(e.DataField, fieldProductAmount1) Then
            ' This is a Grand Total cell.
            If ReferenceEquals(e.ColumnField, Nothing) OrElse ReferenceEquals(e.RowField, Nothing) Then
                e.CustomValue = "Grand Total"
                Return
            End If
            Dim pivot As PivotGridControl = TryCast(sender, PivotGridControl)
            Dim lastRowFieldIndex As Integer = pivot.Fields.GetVisibleFieldCount(PivotArea.RowArea) - 1
            Dim lastColumnFieldIndex As Integer = pivot.Fields.GetVisibleFieldCount(PivotArea.ColumnArea) - 1

            ' This is an ordinary cell.
            If e.RowField.AreaIndex = lastRowFieldIndex AndAlso e.ColumnField.AreaIndex = lastColumnFieldIndex Then
                e.CustomValue = e.SummaryValue.Average
                ' This is a Total cell.
            Else
                e.CustomValue = "Total"
            End If
        End If
    End Sub

End Class
