Imports DevExpress.XtraPivotGrid
Imports DevExpress.Data.PivotGrid
Public Class Form1

    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        CustomerReportsTableAdapter1.Fill(NwindDataSet1.CustomerReports)
    End Sub

End Class
