using System.Windows.Forms;
using DevExpress.XtraPivotGrid;

namespace WinPivotCustomSummaryCellType {
    public partial class Form1 : Form {
        public Form1() {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            
            pivotGridControl1.CustomSummary += new PivotGridCustomSummaryEventHandler(pivotGridControl1_CustomSummary); 
            customerReportsTableAdapter1.Fill(nwindDataSet1.CustomerReports);
            fieldProductAmount1.SummaryType = DevExpress.Data.PivotGrid.PivotSummaryType.Custom;
        }

        private void pivotGridControl1_CustomSummary(object sender, PivotGridCustomSummaryEventArgs e) {
            if (ReferenceEquals(e.DataField, fieldProductAmount1)) {
                // This is a Grand Total cell.
                if (ReferenceEquals(e.ColumnField, null) || ReferenceEquals(e.RowField, null)) {
                    e.CustomValue = "Grand Total";
                    return;
                }
                PivotGridControl pivot = sender as PivotGridControl;
                int lastRowFieldIndex = pivot.Fields.GetVisibleFieldCount(PivotArea.RowArea) - 1;
                int lastColumnFieldIndex = pivot.Fields.GetVisibleFieldCount(PivotArea.ColumnArea) - 1;

                // This is an ordinary cell.
                if (e.RowField.AreaIndex == lastRowFieldIndex && e.ColumnField.AreaIndex == lastColumnFieldIndex) {
                    e.CustomValue = e.SummaryValue.Average;
                }
                // This is a Total cell.
                else {
                    e.CustomValue = "Total";
                }
            }
        }
    }
}
