using System.Windows.Forms;
using DevExpress.XtraPivotGrid;

namespace WinPivotCustomSummaryCellType {
    public partial class Form1 : Form {
        public Form1() {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            
            customerReportsTableAdapter1.Fill(nwindDataSet1.CustomerReports);
            ExpressionDataBinding expression = new ExpressionDataBinding();
            expression.Expression = "Iif(IsTotal([fieldCompanyName]), 'Grand Total', IsTotal([fieldYear]), 'Grand Total', IsTotal([fieldProductName]), 'Total', IsTotal([fieldQuarter]), 'Total', Sum([ProductAmount]))";
            fieldProductAmount.DataBinding = expression;
        }
    }
}
